### ISSUE TITLE
is it Compatible for 3.3?

### ISSUE THREAD

**Issue by Maggan22** [toxyy/anonymousposts#22]
Hi,

what's about 3.3 - is it compatible with it?

**Comment by toxyy** [comment]
If you have never installed it before, and you manually install this pull request:
https://github.com/phpbb/phpbb/pull/5505

then yes.

If you have already installed this extension to version 0.10.0, then run this sql query on your database:
`INSERT INTO `phpbb_config` (`config_name`, `config_value`, `is_dynamic`) VALUES ('anonymous_posts_version', '0.10.0', '0')`

(adjust if you have a different database prefix)

then you can also install the extension.  That pull request is supposed to be merged with 3.3.4, so if it is, then you can just install the extension as normal, without having to manually add the code.
